stages:
  - test

default:
  before_script:
    - apt-get update
    - scripts/install.sh

test0-job:
  stage: test
  script:
    - gtkhafiz --version | grep version

test1-job:
  stage: test
  script:
    - gtkhafiz -v | grep version
